name: The Roastery
favicon: null
layout_spectrum: 0.25125
typography_spectrum: 0.49833
title: The Roastery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6e6d75'
    - '#b9b1a7'
    - '#402c14'
    - '#decebd'
    - '#6d5330'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
