name: The Roastery
favicon: null
layout_spectrum: 0.25125
typography_spectrum: 0.49833
title: The Roastery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#616161'
    - '#c5c5c5'
    - '#878787'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
